### ISSUE TITLE
OnBoarding and notification on small screens

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#434]
On forum, Marie reported a [display bug on small screens](https://forum.cozy.io/t/petit-bug-daffichage-du-calque-notification-sur-iphone/808) during on boarding.

**Comment by m4dz** [comment]
This one is related to the #453, and should be no more exist since we remove the wizards. Notifications pane already has a high z-index value, I think it'll no more be overlayed by any other component.

Note also that, IMHO, it's logic if wizard are above the notification panel as long as they are modals :wink:.

**Comment by poupotte** [comment]
Wizard is no more relevant and panel notification is well managed for small screen.
