### ISSUE TITLE
Redirect after login is broken

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#500]
I was reading a file but got disconnected, so I hit the Login page with the URL https://xxx.cozycloud.cc/login?next=/apps/files/files/… but after login I didn't get redirected.

**Comment by clochix** [comment]
Fixed in cozy/cozy-proxy#160 thank you @poupotte

**Comment by viki53** [comment]
Hi!

I don't know if it's related, but when I log in to my local test Web client I get redirected to a 404 address every time.

So instead of being redirected to `https://127.0.0.1:2223/#home` I end up on `https://127.0.0.1:2223/%23home#home` for example. Same with every URL I can be before I'm logged out (which happened a lot yesterday as I had to update several times.

**Comment by clochix** [comment]
Hi @viki53,
Thanks for reporting, I think I [just fixed the redirection problem](https://github.com/cozy/cozy-proxy/issues/195). The fix should be available in a few days.
