### ISSUE TITLE
client error on intents

### ISSUE THREAD

**Issue by clochix** [cozy/cozy-home#629]
Seen into the logs:
```
error - home:client | {"type":"error","error":{"msg":"Error handling intent: m4rk-suave::null::{\"name\":\"winId\",\"winId\":145019644930500000,\"url\":\"https://xxxx.cozycloud.cc/apps/hastebin/\",\"callId\":\"145019644930500000-1\",\"needResponse\":true}","name":"Error","full":"Error","stack":"Error\n    at https://xxxx.cozycloud.cc/javascripts/app.js:5071:108"},"url":"MainRouter.initialize","line":null,"col":null,"href":"https://yoseph.cozycloud.cc/#apps/hastebin/"}
```

This seems to happen when trying to open the Haste application

**Comment by toddhgardner** [comment]
Hey all, just ran across this in a Google search. I captured a similar error from our TrackJS monitoring today, but I believe this is caused by a Chrome extension. Seeing this nearly identical error on a totally different app reinforces that for me. Probably nothing to worry about :)

All the best! Todd.

**Comment by clochix** [comment]
Thanks for the feedback @toddhgardner.

I only saw this error one time, so your explanation makes sense. @poupotte I think we could close this one.
