### ISSUE TITLE
App's title missing when installing from a Github repo

### ISSUE THREAD

**Issue by nicofrand** [cozy/cozy-home#645]
Using this URL : https://github.com/frankrousseau/HexGL.git, I got "undefined" instead of the application title when cozy displays all the rights the app requires.

![cozy-bug-add-app](https://cloud.githubusercontent.com/assets/3419050/12378515/050bf42a-bd40-11e5-8feb-c16283a8fef6.png)

PS: same with https://github.com/frankrousseau/2048.git and https://github.com/jsilvestre/cozy-esviji.git

**Comment by lemelon** [comment]
It seems that, when you want to upload from the url, all the apps that are not in the marketplace are "undefined". Also, when you use the url and you want to upload an app from the marketplace you only get the description, but not the name. So this problem seems, IMHO, to be global. Maybe that it could be interesting to get all the info of an app only from the package.json file. Do you want me to have a look ?

**Comment by clochix** [comment]
Probably related to cozy/cozy-controller#120
IMHO, we should use informations from `package.json` rather than from our registry every time it is possible.

**Comment by poupotte** [comment]
This issue is fixed in new home version : 2.1.7.
Thanks @clochix
